
li = [1, 2, 3]
print("Original List:", li)
li.append(4)
print("After append(4):", li)
li.extend([5, 6])
print("After extend([5,6]):", li)
li.insert(1, 10)
print("After insert(1,10):", li)
li.remove(3)
print("After remove(3):", li)
li.pop()
print("After pop():", li)
li.sort()
print("After sort():", li)
li.reverse()
print("After reverse():", li)
print("Length:", len(li))
print("Sum:", sum(li))
print("Max:", max(li))
print("Min:", min(li))
print("Sorted:", sorted(li))
print("Reversed:", list(reversed(li)))
print()


print("TUPLE EXAMPLES ")
tp = (10, 20, 30, 20)
print("Tuple:", tp)
print("Count of 20:", tp.count(20))
print("Index of 30:", tp.index(30))
print("Length:", len(tp))
print("Max:", max(tp))
print("Min:", min(tp))
print("Sum:", sum(tp))
print()


print("SET EXAMPLES ")
s = {1, 2, 3}
print("Original Set:", s)
s.add(4)
print("After add(4):", s)
s.update([5, 6])
print("After update([5,6]):", s)
s.remove(2)
print("After remove(2):", s)
s.discard(10)  
print("After discard(10):", s)
print("Union with {5,7,8}:", s.union({5,7,8}))
print("Intersection with {3,4,5}:", s.intersection({3,4,5}))
print("Difference with {5,6,7}:", s.difference({5,6,7}))
print("Symmetric difference with {1,7,8}:", s.symmetric_difference({1,7,8}))
print()


print(" DICTIONARY EXAMPLES ")
d = {'a': 1, 'b': 2, 'c': 3}
print("Original Dictionary:", d)
print("Keys:", d.keys())
print("Values:", d.values())
print("Items:", d.items())
print("Get value for key 'b':", d.get('b'))
d.update({'d': 4})
print("After update({'d':4}):", d)
d.pop('a')
print("After pop('a'):", d)
d.popitem()
print("After popitem():", d)
print("Copy of dictionary:", d.copy())
d.clear()
print("After clear():", d)
print()


print(" COMMON BUILT-IN FUNCTIONS ")
data = [1, 2, 3, 4, 5]
print("List:", data)
print("Any >0:", any(x > 0 for x in data))
print("All <10:", all(x < 10 for x in data))
print("Enumerate:", list(enumerate(data)))
print("Map (square):", list(map(lambda x: x**2, data)))
print("Filter (even):", list(filter(lambda x: x % 2 == 0, data)))
print("Zip:", list(zip(['a','b','c'], [1,2,3])))
